"""
Init test table for first run
"""
from yoyo import step

__depends__ = {}

steps = [
    step(
        """
        create table test (

            test_id int generated by default as identity primary key,
            created_at timestamp without time zone not null default now(),
            language varchar(255) not null,
            event_type event_type not null

        );
        """,
        """
            drop table test;
        """
    )
]
