// Documentation: https://www.dbml.org/docs/
// Online scheme: https://dbdocs.io/

// Build and publish docs to dbdocs.io: dbdocs build dbschema.dbml
// Remove docs from dbdocs.io: dbdocs remove FakedataBackend


Project FakedataBackend {
database_type: 'PostgreSQL'
note: '''
# Randomicu Database

Statistics from Randomicu and Fakedata apps
'''
}

Enum event_type {
  address [note: 'event from Fakedata Address endpoint']
  person [note: 'event from Fakedata Person endpoint']
  random_sentence [note: 'event from Randomicu random-sentence endpoint']
  random_sentences [note: 'event from Randomicu random-sentences endpoint']
  sentence_limits [note: 'event from Randomicu sentence-limits endpoint']
  lorem_limits [note: 'event from Randomicu lorem-limits endpoint']
  lorem_bytes [note: 'event from Randomicu lorem-bytes endpoint']
  lorem_words [note: 'event from Randomicu lorem-words endpoint']
  lorem_paragraphs [note: 'event from Randomicu lorem-paragraphs endpoint']
  lorem_paragraphs_break [note: 'event from Randomicu lorem-paragraphs endpoint with additional linebreak']
  lorem_lists [note: 'event from Randomicu lorem-lists endpoint']
}

Table event as S {
  event_id int [pk, increment]
  created_at datetime [not null, default: `now()`]
  language varchar(255) [not null]
  event_type event_type [not null]

note: "table 'event' contains information about events from Randomicu and Fakedata endpoints"
}
