create type event_type AS enum('address', 'person');


create table if not exists event (
    event_id int generated by default as identity primary key,
    created_at timestamp without time zone not null default now(),
    language varchar(255) not null,
    event_type event_type not null
);
